name: .NET Desktop

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Solution_Name: NdiPlayer.sln                            

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore packages
      run: msbuild $env:Solution_Name -restore
      
    - name: Build Application
      run: msbuild $env:Solution_Name /p:Platform=x64 /p:Configuration=Release /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundle=Always

    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifact: Installer\bin\**\*.msix
        name: ${{steps.previoustag.outputs.tag}}
        tag: ${{steps.previoustag.outputs.tag}}
        token: ${{ secrets.GITHUB_TOKEN }}
