name: Auto-Tag
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag the deployment
        uses: daily-co/create-tag-action@v1.0
        with:
          app-name: 'NdiFullscreenPlayer'
          environment: 'qa'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
